# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iVE6tSh9YLaEL70BOGjfbPLH,iv:PLPZRTjQqO/CA1QZQnsaEfLlWlQ+SS4JjIyf3sRMJ6o=,tag:Mo86QKD9IDB7a7T6JFHmMA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ywgTnwuuH+AXbGY1wK+RtBmVHwiVuh4hdId5FzILRP7SONHrbg==,iv:FJ58o3dMZA7icqQnaBvg9Z9AM1oSmcWlW+uD4Wkh5Ys=,tag:U+nCmYlzJQubOlAEHtd3ug==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:t30AYu0xEsUfavGoK74jzjL7Ksf5GMI=,iv:tN9mUiN1xtHjKQdxUiVJfxLYTanTiIeoEtFahJ0O/TA=,tag:c4p+4YdrJ+4UMCYOfNmkmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtakc0cnF6S3hsU2lBYktt
            VWxjckhSM2w4WTdQT1k5ZURNRlVBdWdUWjA0Ci9xbUh4cnlqSkxodTBRUHlXZHN2
            SEgzZ2k1VHVkZ0xGTmZBS0paRk4yd3cKLS0tIE5xanR0Y2RsNEI4U002K1Q4blN3
            RHVMT3RpaklpSXJSTWd6ZVpPc3FnZ1UK5+WcUVxKHjZ88t+oQ0wxmkqAb2hXkchW
            rB/MxqXhs4et6gvy504f1BCzDI2QwG6/f5kvJOKBuTUcXWGUxaYawQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-11T12:08:03Z"
    mac: ENC[AES256_GCM,data:XA5MvTiOOdMBw8SwFYr4Cx/JQWNgcG1meEWlOfQKLnP1hbnlPBuh8Zr1FWKHMUDTMcVTxN5KAwZSr9wn//QEkx3IgbpmWF/yZy5X9C+MYB2KyI3cfmVYR0hwBtu6uWCq4hzmV+FYcM6++AWaWVEbwqfuNv3vrMFbOo6bjXGxnfI=,iv:zbzMNJz7kwJOFcLJqkPjpSWOOudtdUDw2OgKhaDCp84=,tag:w9b33oCZ4FWFnd/PrxwS8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
