---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  values:
    image:
      repository: pihole/pihole
      tag: "2022.05"
    nameOverride: pihole
    service:
      main:
        ports:
          http:
            port: 80
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_PIHOLE_ADDR}"
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "pihole.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "pihole.${SECRET_DOMAIN}"
            secretName: "pihole-tls"
    persistence:
      config:
        enabled: true
        existingClaim: pihole-data
        subPath:
          - path: etc-pihole
            mountPath: /etc/pihole/
          - path: etc-dnsmasq.d
            mountPath: /etc/dnsmasq.d/
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
