kind: Secret
ansible_user: ENC[AES256_GCM,data:Z0fANxL4,iv:vpNaWhptPn5B6Gg7DHWqyBwzTwQMJhq767sEwTFoXP0=,tag:wnq8ofR2JkqkmT+hRKGL6Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:yKOmlbHivVFl,iv:ZnkgYufTebRLkohWaTcWK9shs6SrHrodSb+cXw2TEKs=,tag:U0IXyKMr5KwW/rDE9zY5kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdGJ3VVRZUThGR3FPMEVk
            TE1sdTgzL3F5MWVTUXhLTDFrN3NoVmNlUTJRClpCUWdsOXVWalkxakpTd2pZL2ty
            UDNoVlFuNndVV3V4OFU0VFBVakx2TncKLS0tIHVUL2EzWVRreW44K3RaWGxsUFBK
            bHBvaytMd3MzUEdMNU1ZV2J1YTNUVjAK9fUshVerOwWkGadRPC7IdhhWS3IowAXj
            m3tD63vPOPqNsKNpxFbYKwGAN77t/mrJdtRbF2e7iA1GMeQjsOe09A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T21:30:07Z"
    mac: ENC[AES256_GCM,data:KVcKHS7zTT3O0xAHXKDcegvsG4YLy8vgDiJVrEXiQu/mfyWxn5lw+tvFa4VUl3viPONEDlE656C9I/tUOLbX3d3hUVcf2Ge6a8e/XY3Dha8Zu86OS5ze+cPDha25X7VwtWoCDdl2W/lZ5YP7WwnjIWD2flA+cKvnbDdy9J3Zdqk=,iv:RCWjjtENiQea8ETMJEdDLk3TSEBIraizGfuAVDRdFlw=,tag:ZM2sMXyLsunJUgbRWHB/lA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
