kind: Secret
ansible_user: ENC[AES256_GCM,data:f6s/X9hJ,iv:TaMovTRv/qaBmYJj5Tx/+kP4vhZnWb9qqJ7ms8CnYrE=,tag:CG+coUA1leZNxX+AadmeeA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/XVix8hyApGS,iv:qeQd7r94E+RY7jPuBvb1xMxDcCAGQJgEP+623z5Yhcw=,tag:U3ax4of+RNMWgrpsHA3Alg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZC9NUFZvY05USW5pNWd6
            eUZlTnZnOW9RUFI1ekRsRmdVTVRLclhPdkdBCk1meHY4dDFILzRGZHhVYkx5Z0tE
            bHNiTTI5MVhjMzY1S0VjQzVEd1hrbXMKLS0tIDZUSm90Z1pZd0pUT25VYzl2VUF1
            VHFKY3V3VnA4MGZIbVVhY0FVRkY3SHMKCJZTf+W76yMFJqUzl/cGAgU4k0zSCQV6
            XbwFykN3iWReo458eVdSpmHoRkERm7Qq2xrcOf9anJj877h53UAcsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T21:30:07Z"
    mac: ENC[AES256_GCM,data:AZku7MjyF9xgB//j/Ib52AXobIzFQMR5kQXs6zjeFdmbCEbuuSJxejTc/bv5PsWCZR1PqY03oUK8UkzlYpY8/dtKi7olhke+ZgwlcpiPg+V/bhS728KvMiH5BIa5HBebiIgPSRmp0kLXOr46nhy8Sm3eKq/XKFlEYGsEQQckg3g=,iv:N4uf39mc/vfyAZfvH4qSWK4ttKbogZpnSmasjt2hbOk=,tag:GBs3Rx3F5uSzLNn4xZciKQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
