---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175
    env:
      TZ: '${TIMEZONE}'
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
          traefik.ingress.kubernetes.io/router.middlewares: 'networking-internal-only@kubernetescrd'
        hosts:
          - host: 'radarr.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'radarr.${SECRET_DOMAIN}'
            secretName: 'radarr-tls'
    persistence:
      config:
        enabled: true
        existingClaim: radarr-data
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: '${NFS_SERVER_ADDR}'
            path: /mnt/redpool/Media/Movies
        mountPath: /media
        readOnly: false
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      supplementalGroups:
        - 1000
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 2000Mi
