---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rook-ceph-mon.secret.sops.yaml
  - rook-ceph-mon-endpoints.yaml
  - operator
  - common
  - common-external
  - cluster-external
