apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
    name: rook-csi-rbd-node
    namespace: rook-ceph
data:
    userID: ENC[AES256_GCM,data:mZ+0oJoCC75FT7UF3+oPSVykbhw=,iv:c3IcY1eBuykRrKA92m/RrN1qpHwl+My50zJt+Y4QWe4=,tag:zPx0GUIkBAnTqtzCq0v6Pg==,type:str]
    userKey: ENC[AES256_GCM,data:9Trm4pwhxcxSS1NNEHKBBLywa11nIgb9hSNPhTmeY2i/KmWHbFe7tpDqlkD9gGkkzrKUV/yGYb0=,iv:n4KgCYmsFFJAKIidPRAnfYGU8fGbWo3VsqQbJUFK97E=,tag:rjtvlB6md6By/08EIZV8Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdlVTZ2k2VkdjZllMNDhY
            TDVEODBJYzFwOUtzQ3FoWXZHK3pBQmV4dVhzCnF0RStQTUZ3eXNWZGh6T2tRMWRp
            M2dYYzRDK2k4UWx1RmlidHJhVUI4VjAKLS0tIDRKeTZqaElBWjRyVDRSK1dQR1NV
            bXpYQWw1bWdrZDVSWVdDaVlnWWdHMWsKLJYm4/blk05FOs9pYWViQIv2f3gN5by9
            RyE0QETXBoQm027ps4aYOvYRukLsb4hNX5fXVY8yCm8f8GOsj7XQMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-28T19:14:18Z"
    mac: ENC[AES256_GCM,data:QD1CFS1QrKPE/RXmW+mZUmFzKuJM54yLWtuWjMt5bURQd6d9wmJ236JkB/kUGlPg5DsBKwGU8MAQOJMhPlfgnoX7NNRjdTnbA1yKVkDVDSkgQpiwM7SvOwYsXTSqzEVcF5KMoYCnHKQoH27asxwL5F5CM0yHb4glPlnxJ0Vm8EU=,iv:CkHR5hfodmm0ekoHZtBpw8xexPm8l27RXUd6Jjh42rI=,tag:zEsheIIZ/4kjOeY5Eh+xWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
