---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: "a=192.168.10.31:6789,b=192.168.10.35:6789,c=192.168.10.35:6789"
  mapping: "{}"
  maxMonId: "2"
