---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: "prox-node-01=192.168.10.31:6789,prox-node-02=192.168.10.33:6789,prox-node-03=192.168.10.35:6789"
  mapping: "{}"
  maxMonId: "2"
