apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
data:
    userID: ENC[AES256_GCM,data:AT128rJNkTXjzyiy3rqFJtyO0mqJIjzj+2HRAg==,iv:f8xAcgNzcuwWH3o01kPeYR3R2jiC+uMcE3quouLL3Jo=,tag:QyQ4QlcUa7VSC4r6gmHndw==,type:str]
    userKey: ENC[AES256_GCM,data:R/DKrWk9Y+L4RDxhauMauDMTBSAol7iIPkiw7+2Ks2gRy1D2vCFsR/6QmSWbb8fyJDMHN5ZfngU=,iv:i/7eqFbTMWquX6d/6IF4MjQLXdQGQ6r7SXdb0iG8Vd8=,tag:pBwEbzMklKTlKHy+ooABTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWUQ4VHhCWGUzMThWV0JM
            dkMxQVNacWdXMUJnejdKR1lIcHlWaFFFd2pVCnZIdEdSTTZ6Rlc1dmNoS09keTBa
            QnlVVlAvZkMwbzJXM3RzQzVnc2M1RG8KLS0tIFUyVWtwSG9PdXJidG5PYUg5TUIx
            OGc5OVBjbXhFaCs4Z2NZMGlTWlRwcGMKppcVWOf0rytFgFCzUr2ToNYiHcCBV3mx
            MavOeRoSXETLLRX2THSnFTENuEdmyRvy1XxdcaOIy2oIZWYU3jgw9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T20:51:42Z"
    mac: ENC[AES256_GCM,data:5fV3l6EXDRkMOX8VeafqApv/dWuQ+6+oTnNucRwhmzpXR4l7BI49+ZLv2Hf9Sx+eGqUB88FTwri4ENaKrXmc7xlF6xZ/Gt0Pi4mXT36TuDEeTYqkCIBsXhxdP5NYVFMYSUC/OucQfo96e2bS8OEtJ4NGZK5FlrU3bla+AhBG+qQ=,iv:TlFwppCQG9MQNB+y2tR9sJRb5/Xpqe75zx6KQpW58wc=,tag:DMPYzUGa1GRclsh49awbqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
