apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
data:
    adminID: ENC[AES256_GCM,data:JYzUP8a5HoyCu5DcEmHT8P0EuTg+NBjWMeyzq2XsIOs=,iv:1Git5V6uiCIEbTkh/nLegfkGGYnAhho+YfsBGHuw0tM=,tag:uNmy8thNEju2eZR+QnGNlQ==,type:str]
    adminKey: ENC[AES256_GCM,data:5MP9NdR3KTxqczMimpRmsAKYOvEToq9WBAu+IdAF8knsoKSCWWouCyCXXL3w5PhHoMzo6FpALNQ=,iv:8lBa8K9ZbkR5sYld14jbPDST9kMa0ZN3k3yxSqKQuVE=,tag:/d0J20ephmigj0xbuBwSQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUHMwdmQxT0s3bnZEZ0Nu
            NnV1WG1IN3AycmxFZjJMZmoyL3MxYTRXTEFnCjF6VG5YTm5nN2lhNU5UR3pVMFpB
            N3Q2OUpwZG16Z09hM2NBc0VoUlI4OHcKLS0tIHZIc1VtbzF1M1JyWDBOdWN0VDJE
            eDBVN0llZDltb0VPbXg3TGIra2Q2Zm8KQsgt2Ydl4pgsZP/0b6F2LqN3+sSZyIra
            iUR+uJhOpMukUsDkJluTRrzcJYJXTadkSjbKKNsaRFv2tTlAaemlhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-30T15:13:54Z"
    mac: ENC[AES256_GCM,data:SYE2PI/ZzAaMOB4naxHe59UamNLFAD0xbCMCzUxcnbiVkRiEDhrXrrP/o+57UKyhJYmrXYFKgrlau5HnWFZ+uA3eFAvzmoJks/6wDQEjfC4JoO5ob1i/8FkdsxoF5G0YTCa5xqYDXNOI5pgqfD7193xfkqb5cmJ2oDZVN2ax4dQ=,iv:ZGndhdtWJpA1KKNyQ0iXJi8Vz+NBTfjwN41oNBmdIjc=,tag:68SXC4WhZqFZZEYWaCcGpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
