# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:GpNJIBvGfXLkI3xiKIvu3owPE+BqyGIW9BbAcVF9kaPrDiBAACoCNOlWQTExIzQerX/emJqtnNT5VsSqboHfYoWAaJsDUW+BYsStp0ySpGWv6kdxwBSfGMz+nudrYctsav4R3kRoH+Jp5j3lVyxEqkjohF2h99Wq,iv:kTxTM6wxkgcbB3wzz2s6TNj3I9dFbKDeGKUD9QAYWtI=,tag:N7+EiQusSLPwJoX5kf56hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNnBZNDdOdkJ6bmhCTDlx
            c1hMZWNhaitscndOYW0yMHltQWgyQTllOFFRCndaSlRQSEFBODNuRUxKcC8waEVO
            WFV4VGppRjYxWXFpcWNUZHRZSDhFY2sKLS0tIFRPZEw5Y3h4RzFLejZhb0I3a0hz
            MkJoQUQ0MWhFdHBlcE5NYkNscWt4elkKoOyHh54fk4k/acqmv72A7GT4w+7GR4Xj
            51QuZlCBpnNhdtFl5/NLG42pniIImGv0EaI7TLHt0tO9PaE98E1EEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T21:43:51Z"
    mac: ENC[AES256_GCM,data:7UFJCjQVmD3ALzqEzZRrgaAd9jkhel7rXrqtwG1H/w1XBNOCcZ+YThG48irGbz8rpd7j8vYzaBjgvLggD+RHMHfLnGB2VGH53/rsv1OUf4yNvhKW/d/iLMgn96XsJ5eiT4MV1DXjT3RuYNMyGDrmRkxp5CKY3iHwHxkK+ay3gFU=,iv:tqwQ+3qnAvXwFU7fuQFZW+9dhrgfLLAq3dApclAbAig=,tag:Uc2aP7B+9DUB5LxCuQr7bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
