# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-credentials
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:9ZxPpIrzgTeTXrXEPcxHVAYcBDVXstZlZRxKGASg/rx3ZyhNscRjqVqeShzOSKxPsIEN4ko+DPggATQATfiYZEOBN/R09ZyAWWwZlpznE+a7h1EIMhNikpY5PB19NyoQ82Bbj1wcOxcdTYKQ+p8YiJ2LrAtI11TC+ebXeLt7ZO4XQkK8AJFiTdFgiQ2u8afBPPQQZLCOS9XlTRxrNGbzlu2cxatpn+HouEVIOwJQuLP0KyJxMIbikfRAB1SLJ0ZgIpxWdl62xvzhWZOwaNQ/7uFiqKNCSedmqciZ8uSJevhSFmNiCelcf5fCRaaAA28XSQUSCwDDjdn8i8WA2orVkrkVs+1LFG1uf4/T+KZFhKMZiP6pAs56X9jn0W+/5TCHZ/wSnFsHh55zKrjOBzHWxopgpn47S+9ErXv8X5EtNzGZUVGDkDe+AHdIg8NvLQ7y4tnfJRFwA3d2XLWAmoA20bkij0ys1O9mLCywDta09tfNBWziNf7AWbDjMBk9jHR5U6nTsf5plZCL7zR15jF2oJArjYzrSyWBIINcVca5x/+uwxmSavMUwGsnE2m3b7pnQMLbAKmzZvcn/4SbiNEdYfGPrtlIlg9izpnVdkVXq7vmXbMWKjJG4hb4APDalHKoRsvwLYKy1Ol8bVYDG/YEE+bIRnBLIUJx5q0N2JJF2FUjiccYV20PpkijjS1uDxp8vdN2Aw==,iv:4z8X0fcz5VO+RBOcQeonwu0x1E3pHDur3xAySP5LcTk=,tag:SOv86URaovGhw1MtlcmMwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:iP0c1bGuTmRyQNmLtAIzssmYhPiF3JJQR4LLLINKKMlv2pJSSCX7q6M+aLyHEgLYzyqat7Dw6qpkyC16K9b7M3CW6U37LrFM9swm/sG/3un2rcD7ngY/h8A2Y4uoAk39BNvAGp3IV808XOcbfghRyyBS1LLQFZo3gbFJ11yIo34SeGh8s/jWY+meUKVucZRqws8U2A8e7+9kGBnfFaada8d1sMQCR1f+xtUlmpwOwYTQBg+ukrOkProdC25o7xlMLfuGkBVLPVNV38ekMp/j4dEp9JjDEd7yW1spAhCiN7QNI/HU,iv:H+M1wvFzkDO2i+yIWF8eCQLDdVvZQmrBeXy+xur3OD8=,tag:vPwYtYgSH6zvNuK+383M2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRjJMaDZkV0VGZm9WMzQw
            T1dTa2NFbkZCMmw3Z3RNcVZnclpYd3Ntb0dJCnkvQ3FCVi9IMXRST1BlVzAyeWJK
            WHdncmJ1TGtXZDFETlJzVGZGeWVxRDgKLS0tIDM1ZHVrcXQ4R0haTTJXYzZuWWJS
            MHFNMGZSMWZLTVIyVnlSenh4QXJhK00Kv6R3oq7e4AthgFiRf6dZb/F9UABXw8Rw
            9ZfLXYr13RE5R/75oUklwznRU5CpCKevpyymY+krODwDKPwpvGBxxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T23:44:06Z"
    mac: ENC[AES256_GCM,data:C4AFfByW6wmsMpphCtJ76M7EtBhfHq8lya5P8W8dUHsco1rkH191ygD1WDiVzaCvHCwzGxFpSNn9eC/OlrSmID8R/EX/EVmwM1W6q5URfILNi9G0jYMoTVLNpw3sNI1WKQZKdG5IdfTfhZ0hi/tRh0MneXxOypTMovzju+/vsu8=,iv:19NNZGK+I65Dy7rYH12ZKB5hRoNgZJ4aqjyCBGVxRc4=,tag:GPhlBmc+8XDSUBuLiH2ecg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
