# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ssh-credentials
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:E9oSuw5YOYrEVDWf8xjLfUnM6cpI5cc+6iV23R5FXzZ+YAY9RUZOAnmey7dUWB+BBY3jhQxH9YChz6S0tToDXVH8nnfHu/FxjAXyboEz1uZyDE2+psbPs4sxTN8fJyfHulMHlD+VxrSKLuD6Zrg4ttou4vFQN+repZWIq1LzaxoQdkQK6eHuxdrFJzGqqklM5MXce6+H/mba6K87hssiEGKDaUAHAfmCr1IFTjFZADK6+tW/NQt37esOwuCuHjGF8HY5cH2N0bA5RCyXXu6hnBDGdR+n9M6B4Hg1FmkeMztbMei2,iv:nUc02AYp/Q/8vy91gbSAogovrjzANI3iuSjfn3jEr44=,tag:ZIFSfZZZ0OgDv0twbBdHjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y6YSNwltlT+0fzxshXLexNoKH+DO4OgUHEmUGq+rkbgo/xEePtRBA665UqAvSDGSnGkO6zy20BP+Ws6CuqBac6Vp+y+MV90XuWODkLST9sBJHe+LyUSCyWBIH4ZcO1cXyyTcACx9Rb7q0hbnfqQSjGhP9R6X1vGiLqcdPmSsDSzWsRzjp5CD3spBe5zFBV6y/NIsnVqZohsQu8kuprCf2te5EOMjqRQLopyHr0ElfB4aGuz73mQiWxVhk0WhwIKiG8zuSQsDUESWMbCiy4XSjSw/m7IIiFy/6dc53VgTocigb/Db,iv:AdovJ7ys/78cN/69IufBOXVYIdxvSOt8HkcPDYANbfA=,tag:oZkx6d4al/X3KFxZDQkQXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k59nyf7q399t0emedp99grcsrycdfk4q48k2uyg4krchu5ttqsgqu2td0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQUJwNGVIUU14cFVwMGVB
            OWFaaThWZ2FsQmk4MUhQcVpmSlBJdGlxbVEwCjFXN2c3R0tVcHNsVjBpL0Y0c2dP
            SjBlVjBQZXppSDV2YW9MYkcySmJrVE0KLS0tIGlSZldGc1N1TmxyaFFBRGllSVRM
            enRuZGtjVUtzQWVMR2g4aVhlN0xEamMKJbeXe08J65lGsq8MkeE6y/4m7Gu5CD0k
            K2AeV5GBcbwF0yGG0VsWSxBaDOaSDxZL0WVFy7+kdWTO06oS8oBlCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T22:56:51Z"
    mac: ENC[AES256_GCM,data:YvjLgk9yOplSSKz1hhP5Ro+LlVycEv4YlNA0FVr3wWNV/2Ww/0i/+fJrW35OpUScaaBwuZJGSrlY/Z6Ul6hA7tmOxzxAEXfjoYRLkRqGYozdihy2E0/VI6kuEEYm+9xBkHHTzpyeyvSZOwC+Lpf9LSsWC5qxdTjK5EfMy8Yaxik=,iv:JWRLhosdjepheNvf5KK6lq0iWUCXU5BTHuUOdv3zXHc=,tag:YUklYrhGfpRJQMOv4jX4bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
